set_property PACKAGE_PIN R2 [get_ports {sayi1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sayi1[2]}]
set_property PACKAGE_PIN T1 [get_ports {sayi1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sayi1[1]}]
set_property PACKAGE_PIN U1 [get_ports {sayi1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sayi1[0]}]

set_property PACKAGE_PIN W16 [get_ports {sayi2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sayi2[2]}]
set_property PACKAGE_PIN V16 [get_ports {sayi2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sayi2[1]}]
set_property PACKAGE_PIN V17 [get_ports {sayi2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sayi2[0]}]

set_property PACKAGE_PIN U16 [get_ports {toplam[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {toplam[0]}]
set_property PACKAGE_PIN E19 [get_ports {toplam[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {toplam[1]}]
set_property PACKAGE_PIN U19 [get_ports {toplam[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {toplam[2]}]
set_property PACKAGE_PIN V19 [get_ports {toplam[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {toplam[3]}]
