set_property PACKAGE_PIN R2 [get_ports {num1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num1[3]}]
set_property PACKAGE_PIN T1 [get_ports {num1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num1[2]}]
set_property PACKAGE_PIN U1 [get_ports {num1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num1[1]}]
set_property PACKAGE_PIN W2 [get_ports {num1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num1[0]}]

set_property PACKAGE_PIN W17 [get_ports {num2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num2[3]}]
set_property PACKAGE_PIN W16 [get_ports {num2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num2[2]}]
set_property PACKAGE_PIN V16 [get_ports {num2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num2[1]}]
set_property PACKAGE_PIN V17 [get_ports {num2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num2[0]}]

set_property PACKAGE_PIN U16 [get_ports {res[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {res[0]}]
set_property PACKAGE_PIN E19 [get_ports {res[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {res[1]}]
set_property PACKAGE_PIN U19 [get_ports {res[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {res[2]}]
set_property PACKAGE_PIN V19 [get_ports {res[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {res[3]}]
set_property PACKAGE_PIN W18 [get_ports {res[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {res[4]}]
set_property PACKAGE_PIN U15 [get_ports {res[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {res[5]}]
set_property PACKAGE_PIN U14 [get_ports {res[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {res[6]}]
set_property PACKAGE_PIN V14 [get_ports {res[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {res[7]}]

