set_property PACKAGE_PIN R2 [get_ports {sayi1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sayi1[3]}]
set_property PACKAGE_PIN T1 [get_ports {sayi1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sayi1[2]}]
set_property PACKAGE_PIN U1 [get_ports {sayi1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sayi1[1]}]
set_property PACKAGE_PIN W2 [get_ports {sayi1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sayi1[0]}]

set_property PACKAGE_PIN W17 [get_ports {sayi2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sayi2[3]}]
set_property PACKAGE_PIN W16 [get_ports {sayi2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sayi2[2]}]
set_property PACKAGE_PIN V16 [get_ports {sayi2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sayi2[1]}]
set_property PACKAGE_PIN V17 [get_ports {sayi2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sayi2[0]}]

set_property PACKAGE_PIN U17 [get_ports {btn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[3]}]
set_property PACKAGE_PIN T18 [get_ports {btn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[2]}]
set_property PACKAGE_PIN T17 [get_ports {btn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[1]}]
set_property PACKAGE_PIN W19 [get_ports {btn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[0]}]

set_property PACKAGE_PIN L1 [get_ports {solLed[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {solLed[4]}]
set_property PACKAGE_PIN P1 [get_ports {solLed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {solLed[3]}]
set_property PACKAGE_PIN N3 [get_ports {solLed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {solLed[2]}]
set_property PACKAGE_PIN P3 [get_ports {solLed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {solLed[1]}]
set_property PACKAGE_PIN U3 [get_ports {solLed[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {solLed[0]}]

set_property PACKAGE_PIN W18 [get_ports {sagLed[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sagLed[4]}]
set_property PACKAGE_PIN V19 [get_ports {sagLed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sagLed[3]}]
set_property PACKAGE_PIN U19 [get_ports {sagLed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sagLed[2]}]
set_property PACKAGE_PIN E19 [get_ports {sagLed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sagLed[1]}]
set_property PACKAGE_PIN U16 [get_ports {sagLed[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sagLed[0]}]
